resolver: lts-3.4

packages:
- 'ethereum-test'
- 'ethereum-vm'
- 'merkle-patricia-db'
- 'ethereum-rlp'
- 'blockapps-util'
- 'blockapps-data'
- 'ethereum-encryption'
- 'strato-conf'
- 'strato-adit'
- 'strato-quarry'
- location:
    git: https://github.com/haskoin/haskoin
    commit: b71bcfa4701e129b69776e6951fe0bb7c8b26ea3

extra-deps: 
- Crypto-4.2.5.1
- SHA2-0.2.5
- leveldb-haskell-0.6.3
- murmur3-1.0.0
- nibblestring-0.0.3
- pbkdf-1.1.1.1
- AES-0.2.9
- normaldistribution-1.1.0.3
- milena-0.5.0.1

flags: {}
extra-include-dirs:
- /usr/local/include
extra-lib-dirs:
- /usr/local/lib
