resolver: lts-3.4

packages:
- 'ethereum-test'
- 'ethereum-vm'
- 'ethereum-merkle-patricia-db'
- 'ethereum-rlp'
- 'ethereum-util'
- 'ethereum-data-sql'

extra-deps: 
- SHA2-0.2.5
- haskoin-0.1.0.2
- leveldb-haskell-0.6.3
- nibblestring-0.0.3
- AES-0.2.9
- json-rpc-0.7.0.2
- pbkdf-1.1.1.1

flags: {}
